image: node:latest

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
build:
  stage: build
  script:
    - echo Entered the install phase ..
    - npm run gh-build
    
deploy:
  stage: deploy
  script:
    - echo Entered the install phase ..
    - npm run gh-deploy