stages:
  - install
  - build
  - deploy

install:
    stage: install
    script:
      - echo Entered the install phase ..
      - npm install
      - git checkout
build:
    stage: build
    script:
      - echo Entered the install phase ..
      - npm run gh-build
    
deploy:
    stage: deploy
    script:
      - echo Entered the install phase ..
      - npm run gh-deploy